# Generated by Django 3.1 on 2022-08-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20220819_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='incharge_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='issue.incharge'),
        ),
    ]
