# Generated by Django 3.1 on 2022-08-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20220819_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incharge',
            name='description',
            field=models.TextField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='incharge',
            name='images',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
