# Generated by Django 3.1 on 2022-08-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_auto_20220819_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='room_name',
            new_name='room_no',
        ),
    ]
