# Generated by Django 3.1 on 2022-08-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0010_auto_20220820_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
