# Generated by Django 3.1 on 2022-08-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0011_auto_20220820_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='call_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='token',
            name='served_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
