# Generated by Django 3.1 on 2022-08-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0013_token_is_called'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='call_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
