# Generated by Django 3.1 on 2022-08-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0015_auto_20220820_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display_call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, unique=True)),
                ('d_room_no', models.CharField(blank=True, max_length=100, unique=True)),
                ('d_tok_no', models.IntegerField(null=True)),
            ],
        ),
    ]
