# Generated by Django 3.1 on 2022-08-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0016_display_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display_call',
            name='display_name',
        ),
    ]
