# Generated by Django 3.1 on 2022-08-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0017_remove_display_call_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display_call',
            name='d_tok_no',
        ),
        migrations.AddField(
            model_name='display_call',
            name='d_TOK_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
