# Generated by Django 3.1 on 2022-08-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0018_auto_20220822_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display_call',
            old_name='d_TOK_no',
            new_name='d_tok_no',
        ),
    ]
