# Generated by Django 3.1 on 2023-01-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0019_auto_20220822_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_missed',
            field=models.BooleanField(default=False),
        ),
    ]
