# Generated by Django 3.1 on 2023-01-02 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0020_token_is_missed'),
        ('accounts', '0003_assignroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='issue.token'),
        ),
    ]
